// @vitest-environment node
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { buildMessages, MessagesBuildError } from './build';

let root: string;
let sourceDir: string;
let outputDir: string;

function writeSource(path: string, content: unknown) {
  const fullPath = join(sourceDir, path);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, typeof content === 'string' ? content : JSON.stringify(content));
}

function readOutput(locale: string): unknown {
  return JSON.parse(readFileSync(join(outputDir, `${locale}.json`), 'utf-8'));
}

describe('buildMessages', () => {
  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'i18n-builder-'));
    sourceDir = join(root, 'source');
    outputDir = join(root, 'out');
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('nests each file under its folder path and merges files of the same locale', () => {
    writeSource('landing/home/en.json', { HomePage: { title: 'Hello' } });
    writeSource('landing/en.json', { shared: 'Shared' });
    writeSource('landing/home/es.json', { HomePage: { title: 'Hola' } });

    const built = buildMessages({ sourceDir, outputDir });

    expect(built).toEqual(
      expect.arrayContaining([
        { locale: 'en', namespaces: 1 },
        { locale: 'es', namespaces: 1 },
      ]),
    );
    expect(readOutput('en')).toEqual({
      landing: { shared: 'Shared', home: { HomePage: { title: 'Hello' } } },
    });
    expect(readOutput('es')).toEqual({ landing: { home: { HomePage: { title: 'Hola' } } } });
  });

  it('strips route groups from the namespace', () => {
    writeSource('(marketing)/about/en.json', { title: 'About' });

    buildMessages({ sourceDir, outputDir });

    expect(readOutput('en')).toEqual({ about: { title: 'About' } });
  });

  it('keeps files at the source root at the top level', () => {
    writeSource('en.json', { metadata: { title: 'App' } });

    buildMessages({ sourceDir, outputDir });

    expect(readOutput('en')).toEqual({ metadata: { title: 'App' } });
  });

  it('removes compiled catalogues of locales that no longer have sources', () => {
    writeSource('en.json', { title: 'App' });
    mkdirSync(outputDir, { recursive: true });
    writeFileSync(join(outputDir, 'fr.json'), '{}');
    writeFileSync(join(outputDir, 'en.d.json.ts'), '// generated by next-intl');

    buildMessages({ sourceDir, outputDir });

    expect(() => readOutput('fr')).toThrow();
    expect(readFileSync(join(outputDir, 'en.d.json.ts'), 'utf-8')).toContain('next-intl');
  });

  it('throws without writing anything when a source file is not valid JSON', () => {
    writeSource('en.json', { title: 'App' });
    writeSource('home/en.json', '{ broken');

    expect(() => buildMessages({ sourceDir, outputDir })).toThrow(MessagesBuildError);
    expect(() => readOutput('en')).toThrow();
  });

  it('throws when a source file root is not an object', () => {
    writeSource('en.json', ['not', 'an', 'object']);

    expect(() => buildMessages({ sourceDir, outputDir })).toThrow(/root must be an object/);
  });
});
